package com.optimize.kopesa.afis.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MatcherJobHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatcherJobHistoryAllPropertiesEquals(MatcherJobHistory expected, MatcherJobHistory actual) {
        assertMatcherJobHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertMatcherJobHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatcherJobHistoryAllUpdatablePropertiesEquals(MatcherJobHistory expected, MatcherJobHistory actual) {
        assertMatcherJobHistoryUpdatableFieldsEquals(expected, actual);
        assertMatcherJobHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatcherJobHistoryAutoGeneratedPropertiesEquals(MatcherJobHistory expected, MatcherJobHistory actual) {
        assertThat(expected)
            .as("Verify MatcherJobHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatcherJobHistoryUpdatableFieldsEquals(MatcherJobHistory expected, MatcherJobHistory actual) {
        assertThat(expected)
            .as("Verify MatcherJobHistory relevant properties")
            .satisfies(e -> assertThat(e.getRid()).as("check rid").isEqualTo(actual.getRid()))
            .satisfies(e -> assertThat(e.getProducerCount()).as("check producerCount").isEqualTo(actual.getProducerCount()))
            .satisfies(e ->
                assertThat(e.getConsumerReponseCount()).as("check consumerReponseCount").isEqualTo(actual.getConsumerReponseCount())
            )
            .satisfies(e -> assertThat(e.getHighScore()).as("check highScore").isEqualTo(actual.getHighScore()))
            .satisfies(e -> assertThat(e.getFoundMatch()).as("check foundMatch").isEqualTo(actual.getFoundMatch()))
            .satisfies(e -> assertThat(e.getMatchedRID()).as("check matchedRID").isEqualTo(actual.getMatchedRID()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMatcherJobHistoryUpdatableRelationshipsEquals(MatcherJobHistory expected, MatcherJobHistory actual) {
        // empty method
    }
}
