# Spring Boot server port
server.port=1111

# Spring Boot Admin user/uassword
spring.security.user.name=admin
spring.security.user.password=Abcd1234

# Spring Boot Admin title
spring.boot.admin.ui.title=LANG REG BACKEND ADMIN BOARD

# custom property for disable security
spring.boot.admin.security.enabled=false