package com.optimize.kopesa.afis.master.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FingerprintStoreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFingerprintStoreAllPropertiesEquals(FingerprintStore expected, FingerprintStore actual) {
        assertFingerprintStoreAutoGeneratedPropertiesEquals(expected, actual);
        assertFingerprintStoreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFingerprintStoreAllUpdatablePropertiesEquals(FingerprintStore expected, FingerprintStore actual) {
        assertFingerprintStoreUpdatableFieldsEquals(expected, actual);
        assertFingerprintStoreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFingerprintStoreAutoGeneratedPropertiesEquals(FingerprintStore expected, FingerprintStore actual) {
        assertThat(expected)
            .as("Verify FingerprintStore auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFingerprintStoreUpdatableFieldsEquals(FingerprintStore expected, FingerprintStore actual) {
        assertThat(expected)
            .as("Verify FingerprintStore relevant properties")
            .satisfies(e -> assertThat(e.getRid()).as("check rid").isEqualTo(actual.getRid()))
            .satisfies(e -> assertThat(e.getHandType()).as("check handType").isEqualTo(actual.getHandType()))
            .satisfies(e -> assertThat(e.getFingerName()).as("check fingerName").isEqualTo(actual.getFingerName()))
            .satisfies(e -> assertThat(e.getFingerprintImage()).as("check fingerprintImage").isEqualTo(actual.getFingerprintImage()))
            .satisfies(e ->
                assertThat(e.getFingerprintImageContentType())
                    .as("check fingerprintImage contenty type")
                    .isEqualTo(actual.getFingerprintImageContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFingerprintStoreUpdatableRelationshipsEquals(FingerprintStore expected, FingerprintStore actual) {
        // empty method
    }
}
