package com.optimize.kopesa.afis.master.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProcessingFingerprintAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcessingFingerprintAllPropertiesEquals(ProcessingFingerprint expected, ProcessingFingerprint actual) {
        assertProcessingFingerprintAutoGeneratedPropertiesEquals(expected, actual);
        assertProcessingFingerprintAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcessingFingerprintAllUpdatablePropertiesEquals(
        ProcessingFingerprint expected,
        ProcessingFingerprint actual
    ) {
        assertProcessingFingerprintUpdatableFieldsEquals(expected, actual);
        assertProcessingFingerprintUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcessingFingerprintAutoGeneratedPropertiesEquals(
        ProcessingFingerprint expected,
        ProcessingFingerprint actual
    ) {
        assertThat(expected)
            .as("Verify ProcessingFingerprint auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcessingFingerprintUpdatableFieldsEquals(ProcessingFingerprint expected, ProcessingFingerprint actual) {
        assertThat(expected)
            .as("Verify ProcessingFingerprint relevant properties")
            .satisfies(e -> assertThat(e.getRid()).as("check rid").isEqualTo(actual.getRid()))
            .satisfies(e -> assertThat(e.getHandType()).as("check handType").isEqualTo(actual.getHandType()))
            .satisfies(e -> assertThat(e.getFingerName()).as("check fingerName").isEqualTo(actual.getFingerName()))
            .satisfies(e -> assertThat(e.getFingerprintImage()).as("check fingerprintImage").isEqualTo(actual.getFingerprintImage()))
            .satisfies(e ->
                assertThat(e.getFingerprintImageContentType())
                    .as("check fingerprintImage contenty type")
                    .isEqualTo(actual.getFingerprintImageContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcessingFingerprintUpdatableRelationshipsEquals(
        ProcessingFingerprint expected,
        ProcessingFingerprint actual
    ) {
        // empty method
    }
}
